export {
  ApplicationsArt,
  BrokenPathArt,
  CohortLayersArt,
  CohortSeatsArt,
  NoResultsArt,
  NotFoundArt,
  NotificationsArt,
  ProgressArt,
  SubmitArt,
  TaskListArt,
  TimelineArt,
  VerdictArt,
  type SpotIllustration,
} from "./spot-art";
