/** User-facing copy for the multi-step apply wizard. */
export const APPLICATION_WIZARD_COPY = {
  backToHome: "← Back to Home",
  signOut: "Sign Out",
  pageTitle: "Apply to Forgeng",
  stepIndicator: (step: number, total: number) => `Step ${step} of ${total}`,
  steps: {
    basicInfo: {
      title: "Basic Information",
      accountHint:
        "You're applying with your Forgeng account. Make sure your name is correct — it'll be saved to your profile. Your email can't be changed here.",
      nameLabel: "Name",
      namePlaceholder: "Your full name",
      emailLabel: "Email",
    },
    background: {
      title: "Your Background",
      backgroundLabel: "Tell us about yourself",
      backgroundPlaceholder:
        "Where are you coming from? What have you been learning?",
      experienceLabel: "Technical Experience",
      experiencePlaceholder:
        "Any programming languages, tools, or projects you've worked with?",
    },
    motivation: {
      title: "Motivation",
      motivationLabel: "Why do you want to join this program?",
      motivationPlaceholder:
        "What are your goals? How will this apprenticeship help you achieve them?",
    },
    videoIntro: {
      title: "Video Introduction",
      hint: "Please record a short video introducing yourself, about 20–30 seconds long. Just say hello and share a little about who you are — there's no need to make it long or formal.",
      allowCameraLabel: "Allow Camera",
      recordLabel: "Start Recording",
      stopLabel: "Stop",
      rerecordLabel: "Re-record",
      uploadLabel: "Upload Video",
      retryUploadLabel: "Try again",
      countdownLabel: (s: number) => `Recording — ${s}s left`,
      uploadingLabel: "Uploading...",
      doneLabel: "Video uploaded",
      errorLabel: "Upload failed. Please try again.",
      permissionDenied:
        "Camera or microphone access was denied. Please allow access in your browser and try again.",
      unsupported:
        "Your browser does not support video recording. Try Chrome or Firefox.",
    },
    wallets: {
      title: "Withdrawal Address",
      hint: "Stipends are paid in crypto to a single wallet. Choose a chain and enter the address you'd like to be paid on.",
      evmLabel: "EVM Address",
      evmDescription: "Covers Ethereum, BNB Chain, Base, Arbitrum, Optimism, and all other EVM-compatible networks. Starts with 0x.",
      evmPlaceholder: "0x...",
      solanaLabel: "Solana Address (Optional)",
      solanaDescription: "Your Solana wallet address (44 characters, Base58).",
      solanaPlaceholder: "e.g. 7xKX...",
      tronLabel: "Tron Address (Optional)",
      tronDescription: "Your Tron wallet address. Starts with T.",
      tronPlaceholder: "T...",
      atLeastOneHint: "Optional — you can skip this if you prefer.",
    },
    socialProfiles: {
      title: "Social Profiles",
      hint: "Help us get to know you better. LinkedIn, GitHub, and Address are required.",
      linkedinLabel: "LinkedIn",
      linkedinPlaceholder: "https://linkedin.com/in/your-profile",
      twitterLabel: "Twitter / X (Optional)",
      twitterPlaceholder: "https://x.com/yourhandle",
      facebookLabel: "Facebook (Optional)",
      facebookPlaceholder: "https://facebook.com/yourprofile",
      githubLabel: "GitHub",
      githubPlaceholder: "https://github.com/yourusername",
      portfolioLabel: "Portfolio / Website (Optional)",
      portfolioPlaceholder: "https://yourwebsite.com",
      telegramLabel: "Telegram (Optional)",
      telegramPlaceholder: "@username or https://t.me/you",
      whatsappLabel: "WhatsApp (Optional)",
      whatsappPlaceholder: "+1234567890",
      countryLabel: "Country",
      countryPlaceholder: "Select your country",
    },
  },
  actions: {
    back: "Back",
    next: "Next Step",
    submitting: "Submitting...",
    submit: "Submit Application",
  },
  toast: {
    submitSuccess: "Application submitted",
    submitSuccessDescription: "Thanks — we'll be in touch soon.",
    alreadySubmitted: "You've already submitted an application.",
    submitError: "Could not submit your application. Please try again.",
  },
} as const;
